name: Update Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'calendar_template.html'
      - 'docs/index.html'
      - 'docs/styles.css'
      - 'docs/script.js'
  workflow_dispatch:

jobs:
  update-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Update Frontend
      run: |
        go run main.go -update-frontend-only

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages

    - name: Commit and push frontend changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/index.html docs/styles.css docs/script.js
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update frontend" && git push)