name: Generate Calendar

on:
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'configs/**'
      - 'main.go'
      - 'calendar_template.html'

jobs:
  generate-calendar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: |
        go mod download

    - name: Generate Calendar
      env:
        AI_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        AI_MODEL: ${{ secrets.AI_MODEL }}
        DISABLE_AI: false
      run: go run main.go

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages

    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update calendar files" && git push)