name: Generate Calendar

on:
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:
    inputs:
      calendars:
        description: 'Comma-separated list of calendars to build (e.g., Pan-Indian, Gujarati etc). Leave empty to build all.'
        required: false
  push:
    branches:
      - main
    paths:
      - 'configs/**'
      - 'main.go'
      - 'calendar_template.html'

jobs:
  generate-calendar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Generate Calendar
      env:
        AI_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        AI_MODEL: 'claude-3-sonnet-20240229'
      run: |
        if [ -n "${{ github.event.inputs.calendars }}" ]; then
          go run main.go -calendars "${{ github.event.inputs.calendars }}"
        else
          go run main.go
        fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages

    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update calendar files" && git push)